apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8jkq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8jkq
    app.kubernetes.io/part-of: tkrw-pr714-0075-0012-app
  name: devfile-sample-8jkq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8jkq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8jkq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0012-tenant/tkrw-pr714-0075-0012-app/devfile-sample-8jkq@sha256:c1803d99a487baf20eb55ef114d8a6df247a7417a65b0d9d5faba8bfc7857baa
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
